# Generated by Django 3.1.7 on 2021-03-23 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=30)),
                ('yazi', models.TextField()),
                ('olusturma_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('yayinlanma_zamani', models.DateTimeField(blank=True, null=True)),
                ('tur', models.CharField(choices=[('1', 'Deneme'), ('2', 'Oyku'), ('3', 'hikaye')], max_length=5)),
            ],
        ),
    ]
