# Generated by Django 3.1.7 on 2021-03-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'makale', 'verbose_name_plural': 'makaleler'},
        ),
    ]
